//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Windows_Store_Downloader.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Windows_Store_Downloader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] res {
            get {
                object obj = ResourceManager.GetObject("res", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap store {
            get {
                object obj = ResourceManager.GetObject("store", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;!doctype html&gt;
        ///&lt;html lang=&quot;zh-cmn-Hans&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no&quot;/&gt;
        ///    &lt;meta name=&quot;renderer&quot; content=&quot;webkit&quot;/&gt;
        ///    &lt;meta name=&quot;force-rendering&quot; content=&quot;webkit&quot;/&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge,chrome=1&quot;/&gt;
        ///    &lt;!-- MDUI CSS --&gt;
        ///    &lt;link
        ///      rel=&quot;stylesheet&quot;
        ///      href=&quot;https://cdn.jsdelivr.net/npm/mdui@1.0.1/dist/css/mdui.min.css&quot;
        ///      integrity=&quot;s [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string table_1 {
            get {
                return ResourceManager.GetString("table_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;!doctype html&gt;
        ///&lt;html lang=&quot;zh-cmn-Hans&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no&quot;/&gt;
        ///    &lt;meta name=&quot;renderer&quot; content=&quot;webkit&quot;/&gt;
        ///    &lt;meta name=&quot;force-rendering&quot; content=&quot;webkit&quot;/&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge,chrome=1&quot;/&gt;
        ///    &lt;!-- MDUI CSS --&gt;
        ///    &lt;link
        ///      rel=&quot;stylesheet&quot;
        ///      href=&quot;https://cdn.jsdelivr.net/npm/mdui@1.0.1/dist/css/mdui.min.css&quot;
        ///      integrity=&quot;s [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string table_1_cn {
            get {
                return ResourceManager.GetString("table_1_cn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似           &lt;!-- END CHANGE --&gt;
        ///      &lt;/div&gt;
        ///      
        ///      &lt;button class=&quot;mdui-btn mdui-btn-raised mdui-ripple mdui-color-indigo mdui-valign mdui-center&quot;
        ///        onClick=&quot;document.title = &apos;IAMOKAY&apos;;&quot; style=&quot;margin-top: 20px;&quot;&gt;Okay
        ///        &lt;i class=&quot;mdui-icon material-icons&quot;&gt;
        ///        check&lt;/i&gt;&lt;/button&gt;
        ///    &lt;/div&gt;
        ///    &lt;!-- MDUI JavaScript --&gt;
        ///    &lt;script
        ///      src=&quot;https://cdn.jsdelivr.net/npm/mdui@1.0.1/dist/js/mdui.min.js&quot;
        ///      integrity=&quot;sha384-gCMZcshYKOGRX9r6wbDrvF+TcCCswSHFucUzUPwka+Gr+uHgjlYvk [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string table_2 {
            get {
                return ResourceManager.GetString("table_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似           &lt;!-- END CHANGE --&gt;
        ///      &lt;/div&gt;
        ///      
        ///      &lt;button class=&quot;mdui-btn mdui-btn-raised mdui-ripple mdui-color-indigo mdui-valign mdui-center&quot;
        ///        onClick=&quot;document.title = &apos;IAMOKAY&apos;;&quot; style=&quot;margin-top: 20px;&quot;&gt;确认
        ///        &lt;i class=&quot;mdui-icon material-icons&quot;&gt;
        ///        check&lt;/i&gt;&lt;/button&gt;
        ///    &lt;/div&gt;
        ///    &lt;!-- MDUI JavaScript --&gt;
        ///    &lt;script
        ///      src=&quot;https://cdn.jsdelivr.net/npm/mdui@1.0.1/dist/js/mdui.min.js&quot;
        ///      integrity=&quot;sha384-gCMZcshYKOGRX9r6wbDrvF+TcCCswSHFucUzUPwka+Gr+uHgjlYvkAB [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string table_2_cn {
            get {
                return ResourceManager.GetString("table_2_cn", resourceCulture);
            }
        }
    }
}
